name: universal_picture
description: "UniversalPicture is a versatile Flutter library for rendering images regardless of their format or source."
version: 1.0.0
homepage: https://github.com/Novak-Fenocchio/RenderIf.git
repository: https://github.com/Novak-Fenocchio/RenderIf.git

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
